# This file contains type stubs for the aerospike_async.exceptions submodule
# Generated by postprocess_stubs.py

import builtins
import typing
from .._aerospike_async_native import BatchRecord, ResultCode

# Exception classes
class AerospikeError(builtins.Exception):
    """Base exception class for all Aerospike-specific errors."""
    @property
    def in_doubt(self) -> builtins.bool: ...
    @property
    def node(self) -> typing.Optional[builtins.str]: ...
    @property
    def iteration(self) -> typing.Optional[builtins.int]: ...
    @property
    def base_message(self) -> typing.Optional[builtins.str]: ...
    @property
    def sub_exceptions(self) -> typing.Optional[builtins.list]: ...
    def __init__(self, message: builtins.str) -> None: ...

class ServerError(AerospikeError):
    """Exception raised when the Aerospike server returns an error."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False, sub_code: typing.Optional[builtins.int] = None, server_message: typing.Optional[builtins.str] = None, exp_trace: typing.Optional[typing.Any] = None, node: typing.Optional[builtins.str] = None, iteration: typing.Optional[builtins.int] = None, base_message: typing.Optional[builtins.str] = None, sub_exceptions: typing.Optional[builtins.list] = None) -> None: ...
    @property
    def result_code(self) -> ResultCode: ...
    @property
    def in_doubt(self) -> builtins.bool: ...
    @property
    def sub_code(self) -> typing.Optional[builtins.int]: ...
    @property
    def server_message(self) -> typing.Optional[builtins.str]: ...
    @property
    def exp_trace(self) -> typing.Optional[typing.Any]: ...
    @property
    def node(self) -> typing.Optional[builtins.str]: ...
    @property
    def iteration(self) -> typing.Optional[builtins.int]: ...
    @property
    def base_message(self) -> typing.Optional[builtins.str]: ...
    @property
    def sub_exceptions(self) -> typing.Optional[builtins.list]: ...

class UDFBadResponse(AerospikeError):
    """Exception raised when a UDF (User Defined Function) returns a bad response."""
    def __init__(self, message: builtins.str) -> None: ...

class TimeoutError(AerospikeError):
    """Exception raised when an operation times out."""
    def __init__(self, message: builtins.str) -> None: ...

class Base64DecodeError(AerospikeError):
    """Exception raised when Base64 decoding fails."""
    def __init__(self, message: builtins.str) -> None: ...

class InvalidUTF8(AerospikeError):
    """Exception raised when invalid UTF-8 is encountered."""
    def __init__(self, message: builtins.str) -> None: ...

class IoError(AerospikeError):
    """Exception raised for I/O related errors."""
    def __init__(self, message: builtins.str) -> None: ...

class ParseAddressError(AerospikeError):
    """Exception raised when parsing an address fails."""
    def __init__(self, message: builtins.str) -> None: ...

class ParseIntError(AerospikeError):
    """Exception raised when parsing an integer fails."""
    def __init__(self, message: builtins.str) -> None: ...

class ConnectionError(AerospikeError):
    """Exception raised when a connection error occurs."""
    def __init__(self, message: builtins.str) -> None: ...

class ValueError(AerospikeError):
    """Exception raised when an invalid value is provided."""
    def __init__(self, message: builtins.str) -> None: ...

class RecvError(AerospikeError):
    """Exception raised when receiving data fails."""
    def __init__(self, message: builtins.str) -> None: ...

class PasswordHashError(AerospikeError):
    """Exception raised when password hashing fails."""
    def __init__(self, message: builtins.str) -> None: ...

class BadResponse(AerospikeError):
    """Exception raised when a bad response is received."""
    def __init__(self, message: builtins.str) -> None: ...

class InvalidRustClientArgs(AerospikeError):
    """Exception raised when invalid arguments are provided to the Rust client."""
    def __init__(self, message: builtins.str) -> None: ...

class InvalidNodeError(AerospikeError):
    """Exception raised when an invalid node is encountered."""
    def __init__(self, message: builtins.str) -> None: ...

class InvalidNamespaceError(AerospikeError):
    """Exception raised when an invalid namespace is encountered."""
    def __init__(self, message: builtins.str) -> None: ...

class NoMoreConnections(AerospikeError):
    """Exception raised when no more connections are available."""
    def __init__(self, message: builtins.str) -> None: ...

class ClientError(AerospikeError):
    """Exception raised for client-side errors."""
    def __init__(self, message: builtins.str) -> None: ...

class CommitFailedError(AerospikeError):
    """Exception raised when a multi-record transaction commit fails."""
    def __init__(self, message: builtins.str) -> None: ...

class BatchFailedError(ClientError):
    """A batch command failed as a whole.

    ``records`` carries the per-key ``BatchRecord`` outcomes attached to the
    failure: rows the server answered keep their result, unanswered rows
    carry the stamped result code (``TIMEOUT`` on client timeouts) and the
    per-row in-doubt flag.
    """
    records: typing.Optional[builtins.list[BatchRecord]]
    def __init__(self, message: builtins.str) -> None: ...

class MaxErrorRate(AerospikeError):
    """Per-node circuit breaker tripped (client-side, not sent to server)."""
    def __init__(self, message: builtins.str) -> None: ...


class RecordError(ServerError):
    """Record-level server errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class IndexError(ServerError):
    """Index-related server errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class SecurityError(ServerError):
    """Security and authentication server errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class QueryError(ServerError):
    """Query and scan server errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class BatchError(ServerError):
    """Batch subsystem server errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class QuotaError(ServerError):
    """Quota server errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class UdfError(ServerError):
    """Server-side UDF execution errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class RecordNotFound(RecordError): ...
class GenerationError(RecordError): ...
class InvalidRequest(ServerError): ...
class RecordExistsError(RecordError): ...
class BinTypeError(RecordError): ...
class RecordTooBig(RecordError): ...
class BinNotFound(RecordError): ...
class FilteredOut(ServerError): ...
class OpNotApplicable(ServerError): ...
class IndexNotFound(IndexError): ...
class IndexFoundError(IndexError): ...
class NotAuthenticated(SecurityError): ...
class SecurityNotEnabled(SecurityError): ...


# ResultCode is re-exported from the main module for convenience
# It's defined in _aerospike_async_native and added to exceptions submodule at runtime

__all__ = [
    "AerospikeError",
    "ServerError",
    "UDFBadResponse",
    "TimeoutError",
    "BadResponse",
    "ConnectionError",
    "InvalidNodeError",
    "InvalidNamespaceError",
    "NoMoreConnections",
    "CommitFailedError",
    "BatchFailedError",
    "RecvError",
    "Base64DecodeError",
    "InvalidUTF8",
    "ParseAddressError",
    "ParseIntError",
    "ValueError",
    "IoError",
    "PasswordHashError",
    "InvalidRustClientArgs",
    "ClientError",
    "MaxErrorRate",
    "ResultCode",
    "RecordError",
    "IndexError",
    "SecurityError",
    "RecordNotFound",
    "GenerationError",
    "InvalidRequest",
    "RecordExistsError",
    "BinTypeError",
    "RecordTooBig",
    "BinNotFound",
    "FilteredOut",
    "OpNotApplicable",
    "IndexNotFound",
    "IndexFoundError",
    "NotAuthenticated",
    "SecurityNotEnabled",
    "QueryError",
    "BatchError",
    "QuotaError",
    "UdfError",
]
