# This file contains type stubs for the aerospike_async.exceptions submodule
# Generated by postprocess_stubs.py

import builtins
from .._aerospike_async_native import ResultCode

# Exception classes
class AerospikeError(builtins.Exception):
    """Base exception class for all Aerospike-specific errors."""
    def __init__(self, message: builtins.str) -> None: ...

class ServerError(AerospikeError):
    """Exception raised when the Aerospike server returns an error."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...
    @property
    def result_code(self) -> ResultCode: ...
    @property
    def in_doubt(self) -> builtins.bool: ...

class UDFBadResponse(AerospikeError):
    """Exception raised when a UDF (User Defined Function) returns a bad response."""
    def __init__(self, message: builtins.str) -> None: ...

class TimeoutError(AerospikeError):
    """Exception raised when an operation times out."""
    def __init__(self, message: builtins.str) -> None: ...

class Base64DecodeError(AerospikeError):
    """Exception raised when Base64 decoding fails."""
    def __init__(self, message: builtins.str) -> None: ...

class InvalidUTF8(AerospikeError):
    """Exception raised when invalid UTF-8 is encountered."""
    def __init__(self, message: builtins.str) -> None: ...

class IoError(AerospikeError):
    """Exception raised for I/O related errors."""
    def __init__(self, message: builtins.str) -> None: ...

class ParseAddressError(AerospikeError):
    """Exception raised when parsing an address fails."""
    def __init__(self, message: builtins.str) -> None: ...

class ParseIntError(AerospikeError):
    """Exception raised when parsing an integer fails."""
    def __init__(self, message: builtins.str) -> None: ...

class ConnectionError(AerospikeError):
    """Exception raised when a connection error occurs."""
    def __init__(self, message: builtins.str) -> None: ...

class ValueError(AerospikeError):
    """Exception raised when an invalid value is provided."""
    def __init__(self, message: builtins.str) -> None: ...

class RecvError(AerospikeError):
    """Exception raised when receiving data fails."""
    def __init__(self, message: builtins.str) -> None: ...

class PasswordHashError(AerospikeError):
    """Exception raised when password hashing fails."""
    def __init__(self, message: builtins.str) -> None: ...

class BadResponse(AerospikeError):
    """Exception raised when a bad response is received."""
    def __init__(self, message: builtins.str) -> None: ...

class InvalidRustClientArgs(AerospikeError):
    """Exception raised when invalid arguments are provided to the Rust client."""
    def __init__(self, message: builtins.str) -> None: ...

class InvalidNodeError(AerospikeError):
    """Exception raised when an invalid node is encountered."""
    def __init__(self, message: builtins.str) -> None: ...

class NoMoreConnections(AerospikeError):
    """Exception raised when no more connections are available."""
    def __init__(self, message: builtins.str) -> None: ...

class ClientError(AerospikeError):
    """Exception raised for client-side errors."""
    def __init__(self, message: builtins.str) -> None: ...


class RecordError(ServerError):
    """Record-level server errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class IndexError(ServerError):
    """Index-related server errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class SecurityError(ServerError):
    """Security and authentication server errors."""
    def __init__(self, message: builtins.str, result_code: ResultCode, in_doubt: builtins.bool = False) -> None: ...

class RecordNotFound(RecordError): ...
class GenerationError(RecordError): ...
class InvalidRequest(ServerError): ...
class RecordExistsError(RecordError): ...
class BinTypeError(RecordError): ...
class RecordTooBig(RecordError): ...
class BinNotFound(RecordError): ...
class FilteredOut(ServerError): ...
class OpNotApplicable(ServerError): ...
class IndexNotFound(IndexError): ...
class IndexFoundError(IndexError): ...
class NotAuthenticated(SecurityError): ...
class SecurityNotEnabled(SecurityError): ...


# ResultCode is re-exported from the main module for convenience
# It's defined in _aerospike_async_native and added to exceptions submodule at runtime

__all__ = [
    "AerospikeError",
    "ServerError",
    "UDFBadResponse",
    "TimeoutError",
    "BadResponse",
    "ConnectionError",
    "InvalidNodeError",
    "NoMoreConnections",
    "RecvError",
    "Base64DecodeError",
    "InvalidUTF8",
    "ParseAddressError",
    "ParseIntError",
    "ValueError",
    "IoError",
    "PasswordHashError",
    "InvalidRustClientArgs",
    "ClientError",
    "ResultCode",
    "RecordError",
    "IndexError",
    "SecurityError",
    "RecordNotFound",
    "GenerationError",
    "InvalidRequest",
    "RecordExistsError",
    "BinTypeError",
    "RecordTooBig",
    "BinNotFound",
    "FilteredOut",
    "OpNotApplicable",
    "IndexNotFound",
    "IndexFoundError",
    "NotAuthenticated",
    "SecurityNotEnabled",
]
