name: PAC Build & Release

on:
  push:
    branches:
      - feature/shared-workflows-cutover
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  build-release:
    name: Build release
    uses: ./.github/workflows/build-release.yaml
    with:
      dry_run: false
    secrets: inherit
